//! Wave definitions: which enemies spawn, in what order, and how quickly,
//! for each wave of the game.
//!
//! Waves are no longer generated by a formula: each level hand-authors its
//! own wave list in a `<level>.waves.ron` file next to its `.tmx` map (see
//! `src/level.rs`), so a designer can fully control pacing and composition
//! per level.

use crate::enemy::EnemyType;
use serde::Deserialize;

/// A single enemy spawn entry within a wave.
#[derive(Deserialize)]
pub struct SpawnEntry {
    pub kind: EnemyType,
    pub delay_after_previous: f32,
}

#[derive(Deserialize)]
pub struct Wave {
    pub spawns: Vec<SpawnEntry>,
}

/// The full set of hand-authored waves for a level, as deserialized from
/// its `.waves.ron` file.
#[derive(Deserialize)]
pub struct WaveFile {
    pub waves: Vec<Wave>,
}
